{- https://projecteuler.net/problem=2
 -
 - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 -
 - 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 -
 - By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 -
 -}

fibs :: [Int]
fibs = 1 : 1 : zipWith (+) fibs (tail fibs)

sum_even_fib_lt_n :: Int -> Int
sum_even_fib_lt_n n = sum([f | f <- takeWhile (< n) fibs, even f])
